default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: daily_poet_development

test:
  <<: *default
  database: daily_poet_test

production:
  <<: *default
  database: daily_poet_production
  username: daily_poet
  password: <%= ENV['DAILY_POET_DATABASE_PASSWORD'] %>
