source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

# Rails core
gem "rails", "~> 7.0.4"
gem "mysql2", "~> 0.5"
gem "puma", "~> 5.0"

# Frontend
gem "sprockets-rails"
gem "jbuilder"

# Authentication & Authorization
gem "devise"
gem "rack-cors"

# File uploading & processing
gem "image_processing", "~> 1.2"

# Deployment tools
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
